spring:
  application:
    name: newWallet
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: njiru@123
    url: jdbc:postgresql://localhost:5432/newWallet
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        hbm2ddl:
          create_namespaces: true
    generate-ddl: true
